### ISSUE TITLE
Number of Players Doesn't Show Correctly.

### ISSUE THREAD

**Issue by t4r1k58** [fpaezf/CS2-RCON-Tool-V2#24]
![1](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/151680778/3921de2d-1f25-4212-90bc-80ea13bd478b)
This problem appeared after the last major cs2 update.

**Comment by fpaezf** [comment]
Since the last update, the dedicated servers stopped properly calling **EndAuthSession** on client disconnect event which would cause the player count to not go down in the A2S_INFO responses. 

Valve has to fix it in further updates. Meanwhile, this plugin aims to fix that error: https://github.com/Source2ZE/AuthSessionFix

Thanks for the feedback.

**Comment by fpaezf** [comment]
This plugin aims to fix that error: https://github.com/Source2ZE/AuthSessionFix
